spring.application.name=user-login

# 数据库连接
spring.datasource.url=jdbc:mysql://192.168.0.225:3306/user_login?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=happylifeABC00
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis 配置
mybatis.type-aliases-package=com.example.login.entity
mybatis.mapper-locations=classpath:mapper/*.xml

# 服务器配置
server.port=8080
